name: publish book
description: publish book
runs:
  using: composite
  steps:
    - uses: np-complete/build-book-action@v1
      with:
        config: config.ebook.yml
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.BOOK_DEPLOY_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.BOOK_DEPLOY_SECRET_KEY }}
        aws-region: us-west-2
    - run: echo "REPO_NAME=`echo ${{ github.repository }} | cut -d '/' -f 2`" >> $GITHUB_ENV
      shell: bash
    - run: aws s3 cp book.pdf s3://np-complete-books/pdf/${{ env.REPO_NAME }}.pdf --acl public-read
      shell: bash
