name: publish book
description: publish book
inputs:
  config:
    description: config file
    required: false
    default: config.ebook.yml
runs:
  using: composite
  steps:
    - uses: np-complete/build-book-action@de0fd31f822c04d525cb7578eb437d216127398b # v1
      with:
        config: ${{ inputs.config }}
    - uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
      with:
        role-to-assume: arn:aws:iam::009775665146:role/publish-np-complete-book-role
        aws-region: us-west-2
    - run: echo "REPO_NAME=`echo ${{ github.repository }} | cut -d '/' -f 2`" >> $GITHUB_ENV
      shell: bash
    - run: aws s3 cp book.pdf s3://np-complete-books/pdf/${{ env.REPO_NAME }}.pdf --acl public-read
      shell: bash
