name: publish book
description: publish book
runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
      with:
        role-to-assume: arn:aws:iam::009775665146:role/publish-np-complete-book-role
        aws-region: us-west-2
    - run: echo "REPO_NAME=`echo ${{ github.repository }} | cut -d '/' -f 2`" >> $GITHUB_ENV
      shell: bash
    - run: aws s3 cp book.pdf s3://np-complete-books/pdf/${{ env.REPO_NAME }}.pdf --acl public-read --cache-control "max-age=900"
      shell: bash
